### ISSUE TITLE
JavaScript based tools will strip down swagger version to `2`

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-spec#142]
Because in JavaScript `2 === 2.0`, any JavaScript based tool will convert swagger version from `2.0` to `2`.

There are two possible solutions for this. 

1. Use the regular and standard 3 digit version numbers like `2.0.0` and make `swagger` a string
2. Bump up version to `2.1` to avoid this confusion

[Line of code in schema](https://github.com/wordnik/swagger-spec/blob/master/schemas/v2.0/schema.json#L16)

Related https://github.com/wordnik/swagger-editor/issues/191

**Comment by webron** [comment]
I think it's clear by now we're not going to do that, but thanks for the suggestion.
