### ISSUE TITLE
Swagger spec 1.2 inconsistency

### ISSUE THREAD

**Issue by wickedest** [swagger-api/swagger-spec#181]
I noticed that swagger 1.2 recently gained **Info Object**:
https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#513-info-object
https://github.com/swagger-api/swagger-spec/blob/master/schemas/v1.2/infoObject.json

However, **Info Object** was not part of the original 1.2 spec:
https://raw.githubusercontent.com/wordnik/swagger-spec/master/schemas/v1.2/apiDeclaration.json

**Comment by webron** [comment]
Closing this for now. Please reopen if required.
