### ISSUE TITLE
Is petstore-simple.json example valid?

### ISSUE THREAD

**Issue by MrWako** [swagger-api/swagger-spec#192]
If  I take https://raw.githubusercontent.com/swagger-api/swagger-spec/master/examples/v2.0/json/petstore-simple.json save it and then load it into the swagger editor http://editor.swagger.io/ I get this error

Model requires property but it is not defined: name
at definitions ▹ petInput ▹ allOf ▹ 1 ▹ required ▹ 0

Child model declares property already declared by ancestor: id
at definitions ▹ petInput ▹ allOf ▹ 1 ▹ properties ▹ id

is the allOf usage in this and the other examples in https://github.com/swagger-api/swagger-spec/tree/master/examples/v2.0/json correct - or is it something in the editor?

**Comment by webron** [comment]
I'm going to push a fix for this issue, but it's already buried in the commits. I'll just close this for now but it should be available in the next few days (it's already in the 2.0_fixes branch).
