### ISSUE TITLE
handling a property of Anything

### ISSUE THREAD

**Issue by ikitommi** [swagger-api/swagger-spec#20]
hi.

With clojure, it's possible to use `Any` as a field type. How should this be modeled for Swagger?

a pure clojure Schema looks like:

```clojure
(def Pizza {:id    Long
            :name  String
            :meta  Any}
```

valid values for Pizza are for example:

```clojure
{:id 1 :name "kikka" :meta 1}
{:id 2 :name "kukka" :meta nil}
{:id 3 :name "kakka" :meta {:more "stuff" :even {:more "here"}}}
```

for documentation purposes, it would be great to be able to say for return values "there will be something coming behind property :meta", but don't want to break the swagger-gen-clients if there is no way they can understand it.

**Comment by ikitommi** [comment]
yes, this is how to handle it. thanks!

**Comment by zjarkov** [comment]
Could you please paste here some example how it could be modelized in swagger? Maybe I just overlooked something but I still really can't see how to have under one property (in that case called "meta") data with different data type (integer, string, object, ...).

**Comment by fehguy** [comment]
`type: object` is how you make it "anything".

**Comment by zjarkov** [comment]
Hurray, thanks! It's friday afternoon => time to stop thinking and go home...

**Comment by ePaul** [comment]
Hmm, it is a bit strange to assume that `type : object` allows strings, numbers and booleans, which are not objects in JSON.

(I think swagger-codegen maps this to java.lang.Object, which in deed is "anything".)

**Comment by ralfhandl** [comment]
My assumption would have been that an empty schema is "anything".
