### ISSUE TITLE
Load PathItemObject from external resource (a.k.a. self-describing resources, is this possible?)

### ISSUE THREAD

**Issue by tknerr** [swagger-api/swagger-spec#219]
Currently I maintain the specification of my REST service in the hand-written swagger .yaml format.

I'm wondering whether it would be possible to put the swagger compliant description of the resource (a [PathItemObject](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#pathItemObject) that would be I guess) right into the resource itself => so the resource is self-describing and the documentation right beside the code.

E.g. http://acme.com/v1/users/1?describe returns the swagger json PathItemObject to describe itself.

**Comment by webron** [comment]
@tknerr - first, I retract my comment regarding the YAML not being a first class citizen - it is.

Second, do we still have any action items here or can we close this issue?

**Comment by tknerr** [comment]
@webron didn't have the time to try it out yet, but it seems to be possible looking at @mission-liao's pull request: 
https://github.com/mission-liao/pyswagger/pull/21/files#diff-5fe6828151d09e04cd5d6c2d48a67348R15

I'm fine with closing
