### ISSUE TITLE
[spec_2.0] Proposal: Vendor extensions for "Schema" object

### ISSUE THREAD

**Issue by martoe** [swagger-api/swagger-spec#241]
For my current project, I need additional metadata on object definitions (these data is needed by the code generator).
Therefore it would be very helpful to add the possibility of [vendor extensions](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#vendorExtensions) also to the [Schema object](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#schemaObject) type.

**Comment by webron** [comment]
Can you give examples of such meta data?

For 2.0, it's not really an option, but we can look into it for the next version.

**Comment by martoe** [comment]
For example we need to flag all properties that are part of the "business key" (needed for generating the equals() and hashcode() methods). I was thinking of something like:

    definitions:
      Person:
        properties:
          lastName:
            type: string
          firstName:
            type: string
          phoneNumber:
            type: string
        x-unique: [lastName, firstName]

**Comment by webron** [comment]
Okay. Let's see what kind of input other people give here.

**Comment by lukastymo** [comment]
It makes sense to fix this issue also on Property level:

```
  "paths": "...
  "definitions": 
    "Person": 
       "properties": 
           "creditCardNumber": 
              "type": "string",
              "x-property-level-metadata": "abc"
```

**Comment by webron** [comment]
This is updated in the spec, will be updated in the schema soon too.
Apologies for this, it was my oversight as it was meant to be included in the first place.

**Comment by kchan628** [comment]
Hi @webron we are using the swagger parser and we are not able to read out vendor extensions at the property level. Do you know if the swagger parser has been updated yet to do this?

**Comment by webron** [comment]
@kchan628 - which version do you use?

**Comment by dylanowen** [comment]
Hi @webron regarding @kchan628 's comment we are attempting to do this with: swagger-parser-1.0.10, swagger-models-1.5.3, and swagger-core-1.5.3. 

I was looking through PropertyDeserializer.propertyFromNode and it looks like vendor extensions are supported for every property except RefProperty, ObjectProperty, and ArrayProperty. After going through the specification I can't find anything that would prevent those properties from supporting vendor extensions. Are these properties supposed to be excluded from supporting vendor extensions or is this a bug we can fix?

**Comment by webron** [comment]
RefProperty and ArrayProperty can't have vendor extensions. I believe ObjectProperty should, but could be mistaken.

**Comment by jonruggiero** [comment]
@webron - Is there a reason why RefProperty and ArrayProperty cannot have vendor extensions?  Seems like the reason to have vendor extensions at all is that 3rd parties may have custom annotations for any/all properties.

**Comment by webron** [comment]
There are technical reasons, yes. JSON references cannot contain any additional properties. For arrays, structure-wise, it won't be a valid JSON.

**Comment by kchan628** [comment]
Hey @webron,

Here is an example of where I would want to use vendor extensions on RefProperty and ArrayProperty but it is currently not working.

'''
swagger: "2.0"
definitions:

  objectReference:
    type: "object"
    properties:
      id:
        type: "string"
      descriptor:
        type: "string"

  employee:
    type: "object"
    properties:
      name:
        type: "string"
      city:
        $ref: "#/definitions/objectReference"
        x-listing: "<city-listing-url-goes-here>"
      jobs:
          type: "array"
          items:
            $ref: "#/definitions/objectReference"
          x-listing: "<job-listing-url-goes-here>"
'''

**Comment by webron** [comment]
I'm not saying I don't understand the use-case I'm saying JSON Reference doesn't allow any additional properties besides `$ref` and those would be ignored. This is a technical limitation we can't work around. If you need the vendor extensions there, they would have to go inside the model definition itself.

**Comment by kchan628** [comment]
@webron, sorry I updated my comment before I saw your answer. Is the workaround I posted what you mean by going inside the model definition itself? I'm just trying to figure out a way to convey this information that can conform to the spec.

**Comment by kchan628** [comment]
@webron,

how about like so for ref?

  city:
    allOf:
      - $ref: "#/definitions/objectReference"
      - x-listing: "<city-listing-url-goes-here>"

and like so for array?

  jobs:
    type: "array"
    items:
      $ref: "#/definitions/objectReference"
    x-listing: "<job-listing-url-goes-here>"

**Comment by kchan628** [comment]
We are trying to adopt the swagger spec but this is blocking us and it would be a shame to have to create our own in house spec.

**Comment by webron** [comment]
You can do it using the `allOf` approach. I'd prefer 'duplicating' the definition to doing that, but either works.

**Comment by kchan628** [comment]
Ok thanks @webron,

So to summarize it sounds like:

1) we can use `allOf` to combine a `$ref` with a `x-` extension
2) swagger parser should be updated to set vendor extensions for ObjectProperty

And I am unclear whether we have agreement on

3) if swagger parser should be updated to set vendor extensions for ArrayProperty?

**Comment by webron** [comment]
3) it should not.

**Comment by kchan628** [comment]
@webron,

In that case, is it valid to set the `x-` vendor extension as a root level array definition and then reference that in a property via a ref?

~~~
swagger: "2.0"
definitions:
  jobs:
    type: "array"
    items:
      $ref: "#/definitions/objectReference"
    x-listing: "<job-listing-url-goes-here>"
employee:
    type: "object"
    properties:
      jobs:
        $ref: "#/definitions/jobs"
~~~

Or is that not allowed either?

Thank you. Sorry for all the questions! Just want to get this right!

**Comment by webron** [comment]
Sorry, must be the late hour. Yes, it would be valid to include a vendor extension in an ArrayProperty just like any other Property type (except for References). Apologies for the confusion.

**Comment by kchan628** [comment]
perfect! thanks
