### ISSUE TITLE
POST formData not working

### ISSUE THREAD

**Issue by clickslide** [swagger-api/swagger-spec#247]
I'm trying to send a simple string as a POST parameter in swagger 2.0. However, I cannot seem to get it to work.

````
    post:
      summary: POST simple parameter
      description: Test
      consumes:
        - application/x-www-form-urlencoded
      parameters:
                   {
                        "name": "_method",
                        "in": "formData",
                        "description": "testing",
                        "required": true,
                        "type": "string",
                        "format": "string"
                    }
````

When I view a log of the $_POST details in my PHP server, the array is empty. It should contain the "_method" parameter. What am I missing?

**Comment by webron** [comment]
You're mixing here YAML and JSON which is probably not the best idea.

How are you testing it, using swagger-editor or swagger-ui?

As a side note, the `"format"` is not necessary in this case.

**Comment by clickslide** [comment]
Hi, 
thanks for the quick reply. I'm not actually mixing, I just used the JSON output from the swagger-editor to post to this issue. I'm using the editor to test, but everything is in YAML in the editor. I'm not actually using JSON for my testing.

**Comment by webron** [comment]
Okay, then if you're testing with the swagger-editor and not getting the expected results, please open the issue on the swagger-editor repository and its developers will look into the issue.

**Comment by clickslide** [comment]
ok, thanks
