### ISSUE TITLE
uri format for the host should be hostname

### ISSUE THREAD

**Issue by casualjim** [swagger-api/swagger-spec#249]
The swagger spec defines the host property with format uri, then proceeds with a pattern to disallow schemes.  This is not a valid uri.

```json
{
  "host": {
    "type": "string",
    "format": "uri",
    "pattern": "^[^{}/ :\\\\]+(?::\\d+)?$",
    "description": "The fully qualified URI to the host of the API."
  }
}
```

The json schema spec is a bit unclear on relative references and whether or not they are allowed. However the URI (RFC 3986) is very clear about the fact that a relative reference not starting with // is a relative path not a hostname. This is contradictory to the pattern because it doesn't allow for / or : 
The usage of the word URI is confusing because an uri surely should allow a scheme.

I think the intended definition of the host property is this:

```json
{
  "host": {
    "type": "string",
    "format": "hostname",
    "description": "The fully qualified hostname for the API."
  }
}
```

I am considering the jsonschema test suite as the source of truth of what a uri format means, because that's what the implementations use. And so if we want consistency we should not diverge from what is in that test suite. 

Extra info:
relative reference uri spec: https://tools.ietf.org/html/rfc3986#section-4.2
https://groups.google.com/d/msg/json-schema/91Xk-ebRw3o/MsKUkFYQRkEJ
hostname: http://json-schema.org/latest/json-schema-validation.html#anchor114
uri: http://json-schema.org/latest/json-schema-validation.html#anchor123
https://github.com/zaggino/z-schema/issues/18
https://github.com/json-schema/JSON-Schema-Test-Suite/issues/58

**Comment by webron** [comment]
Since the "hostname" format doesn't allow ports, it's not going to be the proper solution.

What we'll do is remove the format altogether, and keep the regex as a very basic validation.

Eventually, it's the user's responsibility to provide a proper value as described by the spec.

**Comment by hornc** [comment]
PR that hopefully addresses this: https://github.com/swagger-api/swagger-spec/pull/420

My interpretation is that `host` is NOT a json-schema `hostname` because it can include a port number, and therefore isn't a rcf1034 section 3.1 hostname

**Comment by webron** [comment]
This is now fixed.
