### ISSUE TITLE
Disallow double slash in basepath

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-spec#250]
`basePath: //api` should be forbidden

**Comment by webron** [comment]
Do you refer to the schema?

**Comment by mohsen1** [comment]
yes

**Comment by webron** [comment]
Then that's not really an issue. If the user chooses to input a value that doesn't make sense, it's their problem. We've decided to not include complex regex to validate fields that may catch a few user errors. Just like in mime types, user can input whatever they want and it would still work, not really a concern.

**Comment by mohsen1** [comment]
👍 works for me!

**Comment by webron** [comment]
Cool. There's just a limit to what we can and should check.

That said, the tools around it should be robust enough to deal with malformed values.
