### ISSUE TITLE
How to describe a model in Swagger for an array with simple objects?

### ISSUE THREAD

**Issue by Techbrunch** [swagger-api/swagger-spec#259]
Hello, I cannot find any answer on how to do solve this [Stackoverflow question](http://stackoverflow.com/questions/19585581/how-to-describe-a-model-i-swagger-for-an-array-with-simple-objects) and I'm having the same problem.

I want my model schema to look like this:

```

{
  [
    {
      "id": "int",
      "success": "boolean",
      "error": "string"
    }
  ]
}
```

but right now by using type: "Array" and items: {"$ref": MyModel} the schema look like this:

```
{
  "MyModel": [
    {
      "id": "int",
      "success": "boolean",
      "error": "string"
    }
  ]
}
```

How can I do that ?

**Comment by webron** [comment]
First, which version of Swagger do you use? 1.2 or 2.0?
Second, can you share the full definition you currently have (including MyModel)?
Third, when you say the schema looks like that, do you mean that's how it is displayed in swagger-ui? If so, which version of swagger-ui do you use? You can find out by looking at the top of the swagger-ui.js file.

**Comment by Techbrunch** [comment]
The full definition:

```json
        {
            "path": "\/accounts",
            "operations": [
                {
                    "httpMethod": "DELETE",
                    "nickname": "accountBulkDelete",
                    "summary": "Delete multiple accounts",
                    "description": "Deletes multiple accounts using the given IDs.",
                    "errorResponses": [
                        {
                            "code": 200,
                            "reason": "Bulk delete results",
                            "responseClass": "AccountBulkDeleteList"
                        },
                        {
                            "code": 401,
                            "reason": "You need to be logged in to view this action, but you have not supplied a valid access key."
                        }
                    ],
                    "parameters": [
                        {
                            "paramType": "query",
                            "description": "The IDs of the accounts to delete.",
                            "allowMultiple": true,
                            "dataType": "int",
                            "name": "ids",
                            "required": true
                        }
                    ],
                    "responseCode": 200
                }
            ]
        },
```

The `AccountBulkDeleteList`model:

```json
        "AccountBulkDeleteList": {
            "id": "AccountBulkDeleteList",
            "properties": {
                "accounts": {
                    "type": "Array",
                    "items": {
                        "$ref": "AccountBulkDeleteErrors"
                    }
                }
            }
        },
```

The `AccountBulkDeleteError`:

```json
        "AccountBulkDeleteErrors": {
            "id": "AccountBulkDeleteErrors",
            "properties": {
                "id": {
                    "type": "int",
                    "required": true
                },
                "success": {
                    "type": "boolean",
                    "required": true
                },
                "error": {
                    "type": "string",
                    "required": false,
                    "allowableValues": {
                        "type": "LIST",
                        "values": [
                            "not_found"
                        ]
                    }
                }
            }
        },
```

**Comment by webron** [comment]
That's a very old version of Swagger. What library do you use to produce it?

**Comment by Techbrunch** [comment]
Thanks, we are using our own library for that, the swagger version used is 1.0.2 and the version is not included in the swagger-ui.js. I'm guessing the version we use does not handle this use case ?

**Comment by webron** [comment]
That's a version before my time here, so I can't really say. It is, however, quite old and not really supported anymore. Do you have the option to upgrade or replace the library that you use? Which development language is used here?

**Comment by Techbrunch** [comment]
I will see if updating is an option, the development language is php. What is the recommended library ? I quickly took a look [Swagger-PHP](https://github.com/zircote/swagger-php), is there other good alternatives ?

**Comment by webron** [comment]
For PHP, I can't recommend one implementation over the other, but as far as I can tell, Swagger-PHP is a fairly common one. https://github.com/swagger-api/swagger-spec#php contains the list of the currently known implementations, though it doesn't mean there aren't others as well.

**Comment by Techbrunch** [comment]
Thanks for help. I'm closing this issue.
