### ISSUE TITLE
New open source project for Swagger 

### ISSUE THREAD

**Issue by tarlog** [swagger-api/swagger-spec#261]
Hi,

I wanted to let you know that I have created a new tiny open source project related to Swagger.
The project's goal is to validate the documentation with the actual code and in its initial version, it supports validation of JAX-RS classes for paths and POJOs for definitions.
I'll appreciate if you add the link to this project to README.md under Java section.
 
GitHub: https://github.com/kenshoo/swagger-validator

Thank you!

**Comment by webron** [comment]
@tarlog - that's great! Could you submit a PR against the front-page README and add your library at the appropriate place?

If you have Twitter, let me know and I'll mention you on the announcement.

Also, if you don't mind, please provide me your email in case we need to contact you in the future regarding the library. Feel free to send me your email address directly to ron@swagger.io if you don't want to share it in a public ticket.

**Comment by tarlog** [comment]
Created. See https://github.com/swagger-api/swagger-spec/pull/262

Thanks!

**Comment by webron** [comment]
Thanks, merged :)
