### ISSUE TITLE
Problem about multi fields with formData

### ISSUE THREAD

**Issue by Gwill** [swagger-api/swagger-spec#264]
This is my api spec conf:
![swagger_question](https://cloud.githubusercontent.com/assets/692980/6034829/d264c39c-ac62-11e4-8465-243251601e9a.png)

why is there only generate one field of formData?

**Comment by webron** [comment]
@Gwill - This is an issue with [swagger-editor](https://github.com/swagger-api/swagger-editor) rather than the spec itself. Please open the issue there and we will help you resolve the issue.

**Comment by mohsen1** [comment]
@Gwill This issue is now fixed in Swagger Editor. Thanks for reporting!
