### ISSUE TITLE
MIME types doesn't support underscore symbol

### ISSUE THREAD

**Issue by IvanGoncharov** [swagger-api/swagger-spec#268]
According to [IANA](http://www.iana.org/assignments/media-types/media-types.xhtml), underscores are supported. For example:  "audio/ip-mr_v2.5" or "vnd.ntt-local.sip-ta_remote"

**Comment by webron** [comment]
You mean it's not supported by the json schema?

**Comment by IvanGoncharov** [comment]
Yes. Right now, mimeType  validated against "^[\\sa-z0-9\\-+;\\.=\\/]+$" which is missing underscore.
I create pull request #269

**Comment by webron** [comment]
Thanks, but we're actually going to make it much more permissive soon, see #128. Please subscribe to that issue to get updates.

**Comment by IvanGoncharov** [comment]
Thank you.

**Comment by webron** [comment]
Thank you for taking the time to report it and create a PR though. I really appreciate it. If you have any input with regards to the info at #128, please feel free to add it there.
