### ISSUE TITLE
Swagger 2 AsciiDoc converter

### ISSUE THREAD

**Issue by RobWin** [swagger-api/swagger-spec#271]
Hello,

i'm currently developing a Swagger to AsciiDoc converter. It takes an swagger.json or swagger.yaml as an input file and generates an AsciiDoc file. The primary goal of this project is to simplify the documentation of RESTful APIs. The result is intended to be an easy-to-read, on- and offline user guide, comparable to GitHub’s API documentation.

See https://github.com/RobWin/swagger2asciidoc

Thats why I would be interested in your thoughts and improvement suggestions.

Kind regards,

Robert Winkler

**Comment by fehguy** [comment]
Nice!  You might want to consider bundling your templates in swagger-codegen as a target, as that project has very large distribution, and a single executable for rendering documents.  We can also keep it separate as you have it and you can send a PR to add it to the README for the spec of known tools.

**Comment by webron** [comment]
@RobWin - thanks for that! As Tony mentioned, it would be great if you open a PR against the README if you want to add it to the list of libraries out there. If you give you me your twitter account, I'll also mention you in the announcement.

**Comment by RobWin** [comment]
ok. I'll do that

**Comment by RobWin** [comment]
Have you already announced it?
We plan to integrate the library with springfox

**Comment by webron** [comment]
Apologies, but looks like I haven't. Can make the announcement now if you wish.

**Comment by RobWin** [comment]
Yes, would be great. Thx

**Comment by RobWin** [comment]
But URL is now https://github.com/RobWin/swagger2markup

**Comment by webron** [comment]
Done.
