### ISSUE TITLE
Example for nested arrays

### ISSUE THREAD

**Issue by stevegreatrex** [swagger-api/swagger-spec#273]
If I'm reading the [spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#items-object-) correctly, 2.0 includes support for containers of containers or nested arrays.

Could an example of this scenario be added to the pet store samples?

**Comment by mission-liao** [comment]
Not sure if it's related, but I asked a similar [question](https://groups.google.com/forum/#!topic/swagger-swaggersocket/0uuvNaYxyxQ) in google-group before.

**Comment by fehguy** [comment]
@stevegreatrex yes, that's correct.  The tooling has not caught up yet to support those but that work is in-progress.

**Comment by stevegreatrex** [comment]
I'm trying to update the [swashbuckle](https://github.com/domaindrivendev/Swashbuckle) library to reflect this - could you give me an idea of how you would expect that situation to come out in the final JSON?

**Comment by fehguy** [comment]
A nested array could look like the following:

```json
{
  "type": "array",
  "items": {
    "type": "array",
    "items": {
       "type": "integer",
       "format": "int64"
    }
  }
}```

to represent `[[1,2,3]]`

**Comment by stevegreatrex** [comment]
Perfect, thanks!

**Comment by psy21d** [comment]
YAML

        type: array
        minItems: 2
        maxItems: 2
        items:
          type: array
          items:
            type: string
