### ISSUE TITLE
/api-docs is not displaying paths, but they seem to be available.

### ISSUE THREAD

**Issue by azidahaka** [swagger-api/swagger-spec#281]
(swagger-node-express)
```
{
    apiVersion: "http://localhost:8888",
    swaggerVersion: "1.2",
    apis: [
        {
            path: "/pet"
        }
    ]
}
```

I actually set up another route here for /person, but it is not being shown. When I navigate to api-docs/person however, I am presented with the API.

**Comment by webron** [comment]
This is using which library?

**Comment by azidahaka** [comment]
swagger-node-express

**Comment by webron** [comment]
Then please open the issue on https://github.com/swagger-api/swagger-node-express.
