### ISSUE TITLE
Add additionalProperties to Schema Object Documentation

### ISSUE THREAD

**Issue by Smolations** [swagger-api/swagger-spec#285]
There is an example under the Schema Object definition which uses the "additionalProperties" key, but it is not specified as a possible key in the above spec.

**Comment by analogue** [comment]
So all that is left here is updating the docs in 2.0.md?

**Comment by webron** [comment]
@analogue - you can see the link to the commit in the issue. It'll be available once I merge the fixes with master.

**Comment by analogue** [comment]
@webron As I understand it, there are two things that need to done to resolve this issue.
- Update the jsonschema for the Swagger Specificiation to support `additionalProperties` on object types. This appears in commit 989544c
- Update the list of properties in https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#schema-object to include `additional `additionalProperties`.  This item is the reason for my original question. Without this update, it is not apparent from reading the spec that `additionalProperties` is even supported.

**Comment by webron** [comment]
Oh wow, I was sure I added that as well already. Thanks for bring it up, will be available in the fixes branch shortly.

**Comment by webron** [comment]
Done.

**Comment by Smolations** [comment]
Thanks everyone! :+1:
