### ISSUE TITLE
Either/or required but not both

### ISSUE THREAD

**Issue by marcus-maws** [swagger-api/swagger-spec#286]
Hi,

Is there any way in swagger definitions to specify that either one parameter or another is required, but not both?

e.g. firstname OR fullname is required, but not both

Thanks.

**Comment by mohsen1** [comment]
As of Swagger 2.0 it's not possible. What you can do is defining this logic in your 400 response.

---
swagger: '2.0'
info:
  version: 1.0.0
  title: Pets Store
paths:
  /pets:
    get:
      parameters:
        - name: firstName
          in: query
          description: First Nam
          type: string
        - name: fullName
          in: query
          description: description
          type: string
      responses:
        400:
          description: |
            ##### Bad request
            You have to specifiy either `firstName` or `fullName` parameter.

**Comment by marcus-maws** [comment]
Thanks.  I was thinking of specifying it in the summary possibly in addition to your suggestion with the response.

**Comment by mohsen1** [comment]
#256 is where we're discussion possibility of adding a feature for cases like this in Swagger.Next
