### ISSUE TITLE
GFM syntax in description field

### ISSUE THREAD

**Issue by vpavlushkov** [swagger-api/swagger-spec#292]
The 2.0 markdown document (https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md) states the following for description field: "A short description of the application. GFM syntax can be used for rich text representation." However, when I try to add a table or a list as per guidelines in https://help.github.com/articles/github-flavored-markdown/ I am getting the parser error in editor.swagger.io 
Is this kind of text formatting is actually supported or one can only use *word*, **word** and "<br>" for a line break? Thank you!

**Comment by BigstickCarpet** [comment]
Can you post a sample of your Swagger file?   Are you using JSON or YAML format?  

If you're using JSON, then you'll need to escape any special characters (like newlines and quotes):
````json
description: "| Header 1 | Header 2 | Header 3 |\n|----------|----------|----------|\n| Data 1   | Data 2   | Data 3   |"
````

If you're using YAML, then it's really easy.  YAML allows you to use the pipe symbol (`|`) or greater-than symbol (`>`) to indicate a multiline string.  The difference is that the pipe preserves whitespace, while the greater-than symbol collapses whitespace (the same way HTML does).
````yaml
description: |
    | Header 1 | Header 2 | Header 3 |
    |----------|----------|----------|
    | Data 1   | Data 2   | Data 3   |
`````

**Comment by mohsen1** [comment]
@BigstickCarpet is correct. If you have issues with [Swagger Editor](https://github.com/swagger-api/swagger-editor), please open an issue there. This repository is only for specifications itself.

**Comment by vpavlushkov** [comment]
Thanks a million, @BigstickCarpet and @mohsen1 ! The pipe symbol in YAML format is exactly what I was looking for. I was trying to hold multiline string together by surrounding it by the quotation marks "" but that did not work and HTML tags have proven to be useless (except for <br>).

No, that would be extremely unfair to blame Swagger Editor for my lack of knowledge and experience with Swagger. However, I feel it would be benefitial for the guys like me to have a table and a list to be added to one of the petshop examples.
