### ISSUE TITLE
$ref property of path item object is not able to reference a file in the same domain.  

### ISSUE THREAD

**Issue by RashmiRam** [swagger-api/swagger-spec#295]
The below piece of code is in swagger.json
```js
"paths":{
    "/path/to/action":{
        "$ref":"http://same.domain.com/action_doc.json"
    }
}
```
references another file in the same domain.
As shown in the example here
https://github.com/swagger-api/swagger-spec/blob/master/fixtures/v2.0/json/resources/resourceWithLinkedDefinitions.json#L32

Any advise would be helpful.

**Comment by webron** [comment]
Do you experience an issue with a specific swagger-related tool?

**Comment by RashmiRam** [comment]
Using swagger ui.

**Comment by webron** [comment]
Then please open an issue on swagger-ui :)
