### ISSUE TITLE
ModelsTest does not perform the tests properly

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-spec#302]
[ModelsTest.scala](https://github.com/swagger-api/swagger-spec/blob/2.0_fixes/src/test/scala/ModelsTest.scala) is meant to validate the `definitions` property of the Swagger Object.

However, the validation is not deep. It does not validate the internal Schema Objects against that part of the schema.

For example, if you take https://github.com/swagger-api/swagger-spec/blob/2.0_fixes/fixtures/v2.0/json/models/modelWithExamples.json and change it as such:

```js
{
  "Pet": {
    "properties": {
      "name": {
        "type": "string"
      }
    },
    "required": [
      "name"
    ]
  },
  "Dog": {
    "properties": {
      "id": {
        "type": "integer",
        "format": "int64"
      },
      "name": {
        "type": "string"
      }
    },
    "required": [
      "name"
    ],
    "example123": {
      "name": "Puma",
      "id": 1
    }
  }
}
```
 it should fail validation because `example123` is not a valid property for the Schema Object. However, the test passes with flying colors instead of failing as it should.

**Comment by fehguy** [comment]
this is very, very old
