### ISSUE TITLE
2 fields in an object refer to the same object, the second field object point to null

### ISSUE THREAD

**Issue by Ckim15** [swagger-api/swagger-spec#304]
Hi is the expected result I need it to be after refactoring the code:
```js
Summary:{
                     "productAmount": {
				"currency": "USD",
				"value": 0
			},
			"taxAmount": {
				"currency": "USD",
				"value": 0
			},
			"totalAmount": {
				"currency": "USD",
				"value": 0
			}
}
```

but it displayed 

```js
Summary:{
                     "productAmount": {
				"currency": "USD",
				"value": 0
			}
			
}
```

Here is Swagger.yaml: 

```yaml
Summary:
 properties:
    productAmount:
     $ref: "#/definitions/Amount"
     taxAmount:
        $ref: "#/definitions/Amount"
      totalAmount:
        $ref: "#/definitions/Amount"
Amount:
    properties:
      currency:
        type: string
        default: "USD"
      value:
        type: number
        format: double
 ```

**Comment by webron** [comment]
What's the question?

**Comment by chanthakim15** [comment]
The question is : Is there any other way that I can avoid repetition the code for the above spec?
What I did for now is creating different model (productAmount,taxAmount) and refer it in summary fields.


Summary:
 properties:
    productAmount:
     $ref: "#/definitions/productAmount"
     taxAmount:
        $ref: "#/definitions/taxAmount"
    
productAmount:
    properties:
      currency:
        type: string
        default: "USD"
      value:
        type: number
        format: double
taxAmount:
    properties:
      currency:
        type: string
        default: "USD"
      value:
        type: number
        format: double

**Comment by webron** [comment]
The definition you shared at the top works just as well, you should just add `type: object` to the `Amount`.

**Comment by chanthakim15** [comment]
Ron,
It shares only in the responses Object, but not in the request body.
Not sure what tag we should you. I used schema object in both places:

Here is sample code:

 parameters:
      
        - in: body
          name: requestBody
          required: true
          schema: 
            $ref: "#/definitions/Summary"
          
  responses:
        "201":
          description: success create
          schema:
            $ref: "#/definitions/Summary"
            
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"

**Comment by webron** [comment]
I don't really understand the problem. The specs you're sharing are fine.

**Comment by chanthakim15** [comment]
If we run this sample code, There are 2 different ways of showing for the same Summary object
1. Response Class will be displayed:
{
  "retailAmount": {
    "currency": "USD",
    "value": 0
  },
  "taxAmount": {
    "currency": "USD",
    "value": 0
  }
}

2. And in requestBody in query parameter will be:

{
  "retailAmount": {
    "currency": "USD",
    "value": 0
  }
}

**Comment by webron** [comment]
Are you asking about a problem with a *specific tool* rendering the spec? This is, after all, the repository of the specification itself, and the specification you shared is fine.

**Comment by chanthakim15** [comment]
Ron, 
I am using swagger 2.0, The spec looks fine. Just the way of displaying are different. Could you please run this sample ?

parameters:
      
        - in: body
          name: requestBody
          required: true
          schema: 
            $ref: "#/definitions/Summary"
          
      responses:
        "200":
          description: Success request
          schema:
            $ref: "#/definitions/Summary"
            
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
    

definitions:
 
  
  Summary:
    properties:
      retailAmount:
        schema:
        $ref: "#/definitions/Amount"
      taxAmount:
        schema:
        $ref: "#/definitions/Amount"
        
  Amount: 
   
    properties:
      currency: 
        type: string
        default: "USD"
      value:
        type: number
        format: double
      
  Error:
    required:
      - code
      - message
     
    properties:
      
      code:
        type: string
      message:
        type: string
      moreInfo:
        type: string

**Comment by webron** [comment]
It's obvious you're talking about a specific tool, but I don't know which one. Swagger editor? Swagger UI? Some other tool?

**Comment by Ckim15** [comment]
I am using Swagger UI

**Comment by webron** [comment]
Then next time, please open the issue on Swagger-UI.

Which version of the UI do you use? The situation you describe is a known issue, but I don't recall whether it was resolved already or not. I'd suggest you update to the latest master version, and if that issue persists, search for the open ticket on the matter. If it's not resolved already, it should be part of the next milestone release (M2).
