### ISSUE TITLE
Schema: Allow empty array for parameters

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-spec#305]

**Comment by mhamann** [comment]
So, this is being added to the spec? What's the timeline on this?

The petstore swagger.json on http://petstore.swagger.io is broken as a result of the change already being made to that file but not being referenced by the spec.

In the future, the spec *really* should be updated before the sample JSON is changed, since it will break anyone using it to test their products that are built against the spec.

**Comment by fehguy** [comment]
Matt, it is a bug. This is an OSS project so if the response isn't fast enough please consider a PR. I don't like having defects but it is inevitable

**Comment by webron** [comment]
@mhamann - FWIW, the spec was correct, the schema wasn't.

**Comment by mhamann** [comment]
@webron, thanks for the clarification. Glad to see the validators passing too :-)

**Comment by BigstickCarpet** [comment]
When will the updated Swagger schema be published to NPM?   The version on NPM is six months old and missing a lot of little fixes like this one.

**Comment by webron** [comment]
@BigstickCarpet - which npm is that? I know I've never published anything there.

**Comment by BigstickCarpet** [comment]
@webron - I'm talking about [swagger-schema-official](https://www.npmjs.com/package/swagger-schema-official).  It looks like the npm package is owned by @mohsen1. 

The [package.json](https://github.com/swagger-api/swagger-spec/blob/master/schemas/v2.0/package.json) file is part of the Swagger-Spec codebase, so I assumed that meant the npm package was officially supported/managed by the Swagger team.  Is that not the case?

**Comment by webron** [comment]
There's something behind there. In any case, we'll look into publishing it soon, though a couple of more fixes are pending.

**Comment by BigstickCarpet** [comment]
:+1: Cool, thanks!

**Comment by webron** [comment]
It's actually help if you open a specific issue about it to make sure we remember.
