### ISSUE TITLE
How to doc what JSON fields are required per REST type on an endpoint?

### ISSUE THREAD

**Issue by trusktr** [swagger-api/swagger-spec#306]
As well as what the query params should be?

**Comment by webron** [comment]
Have you looked at the various samples: https://github.com/swagger-api/swagger-spec/tree/master/examples/v2.0/json and https://github.com/swagger-api/swagger-spec/tree/master/fixtures/v2.0/json?

The editor itself contains a few samples as well.

**Comment by trusktr** [comment]
I haven't. Thanks for pointing me in the right direction!
