### ISSUE TITLE
 is "description in Model property" supported in swagger 2.0 Yaml spec?

### ISSUE THREAD

**Issue by Ckim15** [swagger-api/swagger-spec#310]
I tried to run this in swagger ui, it doesn't display the description.
Is the below spec correct? 

Here is an definition of Amount Model:

Amount: 
  properties:
      currency: 
        type: string
        default: "USD"
        description: "This is currency unit"
      value:
        type: number
        format: double
    required:
      - currency
      - value

**Comment by mohsen1** [comment]
If you have an issue with SwaggerUI please open a ticket there:

https://github.com/swagger-api/swagger-ui

**Comment by webron** [comment]
Closing as this was reopened on the right project.
