### ISSUE TITLE
Examples for HTTP responses

### ISSUE THREAD

**Issue by OnamChilwan** [swagger-api/swagger-spec#313]
I was wondering if it was possible to use the examples tag to mock responses for each HTTP status code? For example, I have the following YAML:

```yaml
paths:
  /test:
    get:
      summary: Blah
      description: Blah
      responses:
        200:
          description: Blah
          schema:
            type: string
          examples:
          description: Don't think this
```

I can get an error suggesting "data does not match any schemas from 'oneOf'". Not sure what the syntax is for putting in examples, can't seem to find much and the docs don't show an example.

**Comment by webron** [comment]
Just replied the mailing list as well, but the correct structure maps a mime-type to the example. Something like:

```yaml
paths:
  /test:
    get:
      summary: asfsaf
      description: sfasf
      responses:
        200:
          description: safsaf
          schema:
            type: string
          examples:
            application/json: ...
```

The value is free-form (that is, anything that's valid within a JSON structure).
