### ISSUE TITLE
How to display image logo/text near the swagger logo on the top left?

### ISSUE THREAD

**Issue by Ckim15** [swagger-api/swagger-spec#314]
Hi,

I am wondering if swagger have any tag to display an image or text on the top  left corner near swagger logo; I am currently using swagger spec 2.0.

Here is a nice docs I saw online using swagger 1.2. 
http://www.embeddedcc.com/api-docs/

**Comment by webron** [comment]
This is a question for [swagger-ui](https://github.com/wordnik/swagger-ui).
