### ISSUE TITLE
Decimal type is missed for number format. What is a reason?

### ISSUE THREAD

**Issue by alexkostyanikov** [swagger-api/swagger-spec#316]
Hello,
I am developing a swagger documentation for our API and encountered with misunderstanding:
Decimal type is missed for number format.
https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#data-types

It is very important for us to use Decimal type because of we work with financial systems.
Is it possible to include Decimal type to the spec?
Thank you

**Comment by webron** [comment]
Don't `float` and `double` cover that (and `number` in general)?

**Comment by fehguy** [comment]
i believe (and this may not be what's in the swagger spec), that `number` without a format implies decimal

**Comment by alexkostyanikov** [comment]
There is one more type is used in .Net.
The float keyword signifies a simple type that stores 32-bit floating-point values
The double keyword signifies a simple type that stores 64-bit floating-point values.
The decimal keyword indicates a 128-bit data type.

Now we don't have a way to understand what a type exactly we have to expect.

**Comment by webron** [comment]
The specification can't relate to specific data types in specific languages. Is decimal in .Net fixed or floating point?

The spec does allow you to use whichever format you want, so if you want to call it `float128bit` or `decimal`, you can. It doesn't mean the tools will be able to parse it automatically though. As for the type, it's definitely `number` in this case.

**Comment by alexkostyanikov** [comment]
Decimal is a floating point.

"The spec does allow you to use whichever format you want"
Cool. Where i can read about this? Developers which create frameworks strongly follow to spec instruction.

**Comment by webron** [comment]
https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#data-types, third paragraph.

**Comment by alexkostyanikov** [comment]
ah. thanx a lot

**Comment by fatagun** [comment]
> Don't `float` and `double` cover that (and `number` in general)?

In general, it doesnt. We are building a banking application and decimal is what we only use for money.

**Comment by zijianhuang** [comment]
@fatagun , [WebApiClientGen](https://github.com/zijianhuang/webapiclientgen) has supported decimal inherently for C# and TypeScript. since Swagger lacking of support for decimal, generic and tuple etc. was the primary reason why I had developed WebApiClientGen since 2015.

**Comment by olleharstedt** [comment]
Hm why is this closed if there's no solution yet? For fixed-point datatype representation.

**Comment by olleharstedt** [comment]
> Decimal is a floating point.

Not in a database, it isn't. DECIMAL is a fixed-point type[1].

[1] https://dev.mysql.com/doc/refman/8.4/en/fixed-point-types.html

**Comment by handrews** [comment]
@olleharstedt see the [`format` registry](https://spec.openapis.org/registry/format/) for several fixed- and floating-point solutions.  Be sure to check to see which formats any tools you are using support, as there is no requirement to keep current with the registry.
