### ISSUE TITLE
Is there a spec for defining required HTTP header key val pairs?

### ISSUE THREAD

**Issue by who** [swagger-api/swagger-spec#319]
If an API requires that a certain HTTP header key and value be present, how does the Swagger spec handle the definition of this?

**Comment by mohsen1** [comment]
You can do it via a global parameter definition that is `in: header` and make it required. Then redder to that parameter on all your paths

**Comment by who** [comment]
@mohsen1 Thanks. 

This may not be the right place to ask this, as it's not spec-specific, but in the java world, how are these header parameters practically annotated? Is this accomplished with the [@ApiImplicitParam/@ApiImplicitParams annotation](https://github.com/swagger-api/swagger-core/wiki/Annotations#apiimplicitparam-apiimplicitparams)?

**Comment by fehguy** [comment]
@who that is a java question that belongs here:

github.com/swagger-api/swagger-core

The short answer is, simply put a class variable in your resource and annotate it:

```java
@ApiParam(value = "authorization required to access the resource", required = true)
@HeaderParam("my-header") 
String keyHeader;
```

Please open a ticket there if you need help.
