### ISSUE TITLE
Swagger v2.1.0-M2, type: number

### ISSUE THREAD

**Issue by lifeBCE** [swagger-api/swagger-spec#328]
Seems all number types are not added to the markup when rendered. No error is triggered, just seems to be simply ignored.

```
        "Location": {
            "title": "location",
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "capability": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "latitude": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
```

All three number type parameters are not rendered in UI. I originally had a format of float on each as well and thought that may be the cause so I removed that and still same result. Seems anything that is NOT a string or boolean is ignored. At the very least, all number types are ignored.

**Comment by webron** [comment]
This is an issue for [swagger-ui](https://github.com/swagger-api/swagger-ui/). In the future, please open on the relevant project.

In any case, this is a known issue - https://github.com/swagger-api/swagger-ui/issues/1115.

**Comment by lifeBCE** [comment]
Known as of 14 days ago, got it.

Odd though because here is the same issue in yet a another project: https://github.com/swagger-api/swagger-js/issues/341

Here @fehguy states he addressed the problem in this commit: https://github.com/swagger-api/swagger-js/commit/ab746b87e1d6f2182ae4eff82513b258daa83755

So is it really a swagger-ui issue or swagger-js issue? Seems the latter. I do have a nasty habit of purposely opening issues against wrong projects just to cause confusion. I will take your advice and work on that in the future. :-)

**Comment by webron** [comment]
It's an issue with swagger-js, however most users will not be able to detect that it's an issue with swagger-js as they experience the problem in the ui.
