### ISSUE TITLE
API has more than one body parameter?

### ISSUE THREAD

**Issue by xinyu7git** [swagger-api/swagger-spec#331]
my yml file:      
```yaml
        parameters:
	      #  {"role":"twemproxy","type":"lvs","master_id":1,"standby_id":2} 
	        - name: role
	          in: body
	          description: pool role,twemproxy or mysql.
	          required: true
	          schema:
	           $ref: '#/definitions/Pool'  
	        - name: type
	          in: body
	          description: pool role,twemproxy or mysql.
	          required: true
	          schema:
	           $ref: '#/definitions/Pool'  
```

why swagger-editer only support one body parameter? 
 My rest api 's request data is : {"role":"twemproxy","type":"lvs","master_id":1,"standby_id":2} 
how should i write my yml file?

**Comment by webron** [comment]
That's not two body parameters, that's a single one. One object containing the `role`, `type`, `master_id` and `standby_id` properties.

**Comment by xinyu7git** [comment]
@webron so....how should i write my yml file?

**Comment by xinyu7git** [comment]
![image](https://cloud.githubusercontent.com/assets/3701997/7215527/b782dd80-e60e-11e4-8795-6c8cda34185c.png)

the body object is : 
![image](https://cloud.githubusercontent.com/assets/3701997/7215532/d283bdf2-e60e-11e4-9074-e889b97ac69a.png)

but the parameters is 'a'....  i don't think it looks well to understand....

**Comment by webron** [comment]
It looks like you may have hit a bug in swagger-editor, so please open an issue there. You've named your parameter `data` and that's what it should display.

**Comment by xinyu7git** [comment]
it's my fault to show the parameter'name to 'a'. 
e.... if the parameter is in body,the parameter's name is not used in the request,is it?
so,i think the name should show "role","master_id","standby_id","type".
if the name is data,it makes me confused.

**Comment by webron** [comment]
The name of the `body` parameter is not used in creating the request, it's just used for documentation purposes.

**Comment by xinyu7git** [comment]
ok,thank you.

**Comment by YevheniiHerasymchuk** [comment]
So how it should be defined? 
I also want to define every property of the request.body in `/post` and `/put`. How can I do it?

**Comment by webron** [comment]
How should what be defined?

**Comment by YevheniiHerasymchuk** [comment]
I meant the possibility to define body object with a lot of properties. But solved it in this way:
```
     parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/PostData"
```
