### ISSUE TITLE
in the request form,it can't show the object column in body parameters.

### ISSUE THREAD

**Issue by xinyu7git** [swagger-api/swagger-spec#334]
my body parameters have three column,name/type and config, the type of name/type column is string,but the config column is an object which has other three column, how i should write my yml file? 

in this picture, i use the 'try this operation" function to post data,in the form only name and type are shown,the config column is miss.

![image](https://cloud.githubusercontent.com/assets/3701997/7225004/2187c566-e76c-11e4-9695-650fef5e30e0.png)

![image](https://cloud.githubusercontent.com/assets/3701997/7225008/304ec842-e76c-11e4-998f-805d4f88bcc7.png)

![image](https://cloud.githubusercontent.com/assets/3701997/7225013/3f2e7aec-e76c-11e4-92c8-7d1cdb57ca2d.png)
![image](https://cloud.githubusercontent.com/assets/3701997/7225019/58041194-e76c-11e4-94d5-270ee3a020a5.png)

**Comment by webron** [comment]
This is an issue with the [swagger-editor](https://github.com/wordnik/swagger-editor/) project. Please open the issue there, and in the future, please make sure to open the issue on the project you're having a problem with.
