### ISSUE TITLE
Update Swagger-Schema-Official on npm

### ISSUE THREAD

**Issue by BigstickCarpet** [swagger-api/swagger-spec#335]
The  [swagger-schema-official](https://www.npmjs.com/package/swagger-schema-official) package on npm hasn't been updated in six months.

**Comment by mohsen1** [comment]
It's updated.

**Comment by BigstickCarpet** [comment]
:+1: Thanks!

**Comment by BigstickCarpet** [comment]
The new version on npm is exactly the same as the previous version.    None of the new changes are there.

**Comment by BigstickCarpet** [comment]
Would it be possible to add a version number to the JSON Schema?   That would make it much easier to track schema changes, especially if the version number of the JSON Schema was kept in sync with the version number on NPM.

**Comment by mohsen1** [comment]
My bad, my git origin remote was pointed to my fork. `swagger-schema-official@2.0.0-96305d9` should have the latest

**Comment by BigstickCarpet** [comment]
Thanks @mohsen1!  Looks good now.

**Comment by BigstickCarpet** [comment]
The  [swagger-schema-official](https://www.npmjs.com/package/swagger-schema-official) package on npm has gotten outdated again.  It's been about six months since it was last updated.

@mohsen1 - would you consider making me a [contributor](https://www.npmjs.com/package/swagger-schema-official/access) on the npm package?  If so, I would gladly keep it updated, since I depend on it for [Swagger Parser](https://github.com/BigstickCarpet/swagger-parser).

**Comment by mohsen1** [comment]
@BigstickCarpet published `swagger-schema-official@2.0.0-d79c205`. I don't have access to give you owner permission. I'll try to keep this up to date.

**Comment by BigstickCarpet** [comment]
Thanks, @mohsen1!  It works perfectly.  Thanks for taking care of it so quickly!
