### ISSUE TITLE
Parameter Object has specified but not implemented limits (minimum, maximum)

### ISSUE THREAD

**Issue by mgttlinger** [swagger-api/swagger-spec#339]
The validation of these limits seems not to be implemented in the current version of swagger-ui and should therefore be removed or marked as future functionality.

**Comment by webron** [comment]
I don't really know what you mean, but if it's for swagger-ui, why open the issue here?

**Comment by mgttlinger** [comment]
@webron I posted here because I thought this is an error in the specification rather than the reference implementation.

If you specify a `minimum` and `maximum` for a (`long`) path-parameter the range is not being displayed or validated against. From looking through the source code I did not see these values being used. This lead me to believe this was an error in the specification as it doesn't seem intended to put these values in the json.

Correct me if this is wrong or I misunderstood anything.

**Comment by webron** [comment]
The spec is right. It may just not be fully implemented in the various tools. Take a look at https://github.com/swagger-api/swagger-ui/issues/808 for example.

**Comment by mgttlinger** [comment]
@webron So this is a planned feature? I think it should at least be noted somewhere (in the spec or in the documentation of swagger-ui/-js) which parts of the spec are currently available and which are not.

**Comment by webron** [comment]
It's fairly difficult to keep track of coverage in the range of tools that we and the community offer. 

For our tools, we normally concentrate on the basic functionality that's required to make it work and add on it the features based on our experience and user requests. The best way to get a specific functionality implemented is open an issue on the relevant project. We can't guarantee when it would be implemented (though gladly accept PRs) but it helps us track which features are sought by the users.

**Comment by mgttlinger** [comment]
@webron I do fully understand that it is difficult to track everything that uses your library but from the users perspective it is also difficult to guess what feature specified here he can expect to work.

It has caused me lots of frustration looking for errors in the JSON file I generate and pass to swagger-ui only to find out that this is specified but actually not implemented currently. This could be avoided if there was a roadmap stating which feature is currently implemented or is currently being implemented.

I create PRs where I can but as my expertise as a programmer is not in the field of JavaScript/Web development this is limited to small fixes like adding the missing `{{else}}` to fix  #1113 in swagger-ui.

**Comment by webron** [comment]
I appreciate the frustration, but unfortunately it is well beyond our capacity right now. We're always looking for ways to improve and will take it under advisement, but cannot guarantee such a list would be available in the near future.

**Comment by webron** [comment]
Closing this as an issue for swagger-ui.
