### ISSUE TITLE
How to initialize objects in array

### ISSUE THREAD

**Issue by Ckim15** [swagger-api/swagger-spec#345]
Hi,

I am struggling with initializing mutiple sample objects  in array (**BookCollection**) in Swagger spec.

[

{
  "name" :"New York Magazine",
  "ISSN":  "0028-7369"
},
{
  "name" :"Indianapolis Monthly",
  "ISSN":  "0899-0328"
}

]

**Comment by mohsen1** [comment]
If you want to provide multiple examples, Swagger 2.0 does not support it. Your examples object should have mime-type: example structure. Here you can learn more: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#exampleObject

**Comment by Ckim15** [comment]
Hi, 

Could you please provide a working sample for referred link?

**Comment by webron** [comment]
@Ckim15 - where exactly are you trying to add the sample? In the response? The Schema Object? It's unclear what you're trying to do.

**Comment by Ckim15** [comment]
Ron,

I need to add it in both response and schema object.

**Comment by webron** [comment]
Okay, the value of the examples in both cases is kinda free-form. For the Schema Object, it's pretty much anything, so you can input that as-is.

For the responses, as @mohsen1 stated, you have to assign that value to a specific mime-type. In your case, I imagine it would be `application/json` or an extension of it.

**Comment by webron** [comment]
Closing as answered. Reopen if needed.
