### ISSUE TITLE
Error on the documentation and validation

### ISSUE THREAD

**Issue by AndreJacomeSilva** [swagger-api/swagger-spec#347]
On the Swagger documentation, on the Parameter Object section, it is mentioned that the maxLength and minLength properties are limited to the objects of type integer.
This is wrong, this attributes are available for object of type string - as explained on the JSON schema.

The online validator also throws an false warning «object instance has properties which are not allowed by the schema: [\"maxLenght\"]»

**Comment by webron** [comment]
The documentation says that the *type* of it is integer. It does not say it is limited to anything (even though JSON Schema indeed defines it for strings).

The validator throws a warning because the name of the field is `maxLength` and not `maxLenght`.

**Comment by AndreJacomeSilva** [comment]
Hi Ron,
Thank you very much for the fast reply and sorry to have post such false and basic bug.

Best regards,
André
Sent from my Windows Phone
________________________________

**Comment by webron** [comment]
No worries, better submit something that's not needed than not submitting something that is :)
