### ISSUE TITLE
Expected type string but found type integer

### ISSUE THREAD

**Issue by puneetakhouri** [swagger-api/swagger-spec#350]
Using yamlbeans-1.09.jar to convert my Java objects into yml. For the specific case of creating tag swagger: 2.0, I enter it as a string in my Map in Java like the other objects, all the other objects are rendered without any problem except for this tag wherein it gives the following two errors:
    -Expected type string but found type integer
    -No enum match for: 2

All the other variables are picked up fine except for the version where it identifies the String as integer and I have no clue why. While validating the yml using www.yamllint.com, it turns out to be valid but does not work here. Any help or leads will be appreciated.

**Comment by webron** [comment]
We went over this in SO. This is an issue with yamlbeans that it doesn't respect the original type of the object. You put a string, it converts it to a number. You need to open an issue on the yamlbeans project so that they fix it.
