### ISSUE TITLE
How to remove/replace the swagger icon on the top left of swagger tool 

### ISSUE THREAD

**Issue by Ckim15** [swagger-api/swagger-spec#354]
Hi,

Is there any way that I can change the logo to my favorite one (attached image)? Also I need to customize the green background of that logo. I am currently using swagger-tools.

![swagger logo](https://cloud.githubusercontent.com/assets/10535043/7504885/2e73cbf4-f413-11e4-91a4-d7ad84226188.png)

**Comment by fehguy** [comment]
Hi, I think you should open this in the swagger-tools repo
