### ISSUE TITLE
Default Integer Values Cause Validation Error

### ISSUE THREAD

**Issue by daishisystems** [swagger-api/swagger-spec#357]
I have the following definition in my *.json file:

    "Card": {
        "required": [
            "number",
            "exp_month",
            "exp_year"
        ],
        "properties": {
            "number": {
                "type": "string",
                "default": "0123456789123456"
            },
            "exp_month": {
                "type": "integer",
                "format": "int64",
                "default": 12
            },
            "exp_year": {
                "type": "integer",
                "format": "int32"
            }
        }
    }

Validation fails based on the fact that the default value of exp_month is set to 12. Setting the value to "12" causes successful validation, however, the default value is then of the wrong type in the model.

**Comment by webron** [comment]
Validation from what?

**Comment by daishisystems** [comment]
http://online.swagger.io/validator/debug?url=http://{myUrl}/swagger.json

**Comment by webron** [comment]
Any chance you can share with me the URL? Even in email if you prefer to keep it private.

**Comment by daishisystems** [comment]
http://52.17.253.240/swagger.json

This URL will be active for the next few days, at least.

I've corrected the issue, so this JSON will validate correctly. Update one of the default integer values without including quotes to reproduce.

**Comment by webron** [comment]
Can you host a sample that will not validate? Would just make the testing faster.

**Comment by daishisystems** [comment]
It's under test at the moment, Will have to wait until tomorrow.

**Comment by webron** [comment]
Thanks, got something up and running. There's indeed a problem but I need to investigate it further.

**Comment by webron** [comment]
This is indeed a bug. Please follow https://github.com/swagger-api/validator-badge/issues/23.
