### ISSUE TITLE
Swagger calling schema properties undefined

### ISSUE THREAD

**Issue by huangsam** [swagger-api/swagger-spec#373]
Currently, I'm deploying my documentation using [flask-swagger](https://github.com/gangverk/flask-swagger) with the following Swagger spec for a particular PUT routine:

```yaml
...
        parameters:
          - name: group_id
            in: path
            description: UUID for group
            type: string
            format: uuid
            required: true
          - name: body
            in: body
            required: true
            schema:
              type: object
              properties:
                path:
                  $ref: '#/definitions/group/path'
                type:
                  $ref: '#/definitions/group/type'
              required:
                - path
                - type
...
```

Going to the `/spec` endpoint results in the following JSON for that PUT routine.

![samhua cisco com_20150520_093927900](https://cloud.githubusercontent.com/assets/515617/7736402/5ef79216-fef8-11e4-9ea1-b47a6da3cfa7.png)

As you can see, the JSON does seem to be visible. Thus, I would expect the schema to populate for the body parameter that I created for that PUT routine. However, the Swagger UI is not detecting the schema properties. Instead, it is marking the data type for the body as `undefined`

![samhua cisco com_20150520_094100664](https://cloud.githubusercontent.com/assets/515617/7736404/6234291c-fef8-11e4-9f80-ea84babc5678.png)

Not sure what's going on at this point, whether my spec is incorrect or that the UI is acting weird, so any help is appreciated.

**Comment by webron** [comment]
This is an issue for [swagger-ui](https://github.com/swagger-api/swagger-ui). Please reopen there.
