### ISSUE TITLE
Extensibility of Schema objects? Spec says no, json schema says yes?

### ISSUE THREAD

**Issue by christav** [swagger-api/swagger-spec#375]
Should we be able to have "x-" extension properties in schema objects in swagger documents? The spec says nothing about extensions in schema objects, so I assume that means no extensions. However, the json schema document (see https://github.com/swagger-api/swagger-spec/blob/38bc48c3282271869100791d026a33e514d6ff7e/schemas/v2.0/schema.json#L891) explicitly allows "x-" properties.

Which is intended to be correct, and if it's the spec, any chance to add extensions on schema objects in future versions?

**Comment by webron** [comment]
This is my bad, sorry. Vendor extensions will are meant to be part of most, if not all the objects  in the spec. I need to go over it and update both the spec and the schema. If you already use them in Schema Objects, that's perfectly fine.

**Comment by webron** [comment]
This is updated in the spec, will be updated in the schema too soon.
