### ISSUE TITLE
Separate list of Swagger 2.0 libraries.

### ISSUE THREAD

**Issue by IvanGoncharov** [swagger-api/swagger-spec#376]
It's really useful to have [list](https://github.com/swagger-api/swagger-spec#additional-libraries) of all Swagger related projects.
Problem with it, is that big percentage of projects support only `1.2` version.
Many of the projects doesn't even specify Swagger version in README file.

Good example is [swagger-node-express](https://github.com/swagger-api/swagger-node-express).
I wasn't sure which version it supports until I found this [line](https://github.com/swagger-api/swagger-node-express/blob/master/lib/swagger.js#L49).
My concern is that many new users will stuck with `1.2`, without even knowing about current `2.0` version.

Simplest solution will be to split list into two one for libraries that supports `2.0`  and another for `1.2` only libraries.
Better solution is to create small badges `1.x` and `current`(for current version of spec) and add them into existing list.

**Comment by webron** [comment]
We're reworking the swagger.io website as you may have seen in the announcement we've made and that would be part of it.

Keeping the issue open until it's done.

**Comment by webron** [comment]
This is done now, thanks.
