### ISSUE TITLE
Additional api_key parameters to Security Scheme Object name field

### ISSUE THREAD

**Issue by fantasticfears** [swagger-api/swagger-spec#379]
At Discourse, the API is enforced by a `api_key` and `api_username`. However, the name field only support a string. It's not possible to add more parameters into it.

Reference:
- https://meta.discourse.org/t/discourse-api-documentation/22706
- https://github.com/fantasticfears/discourse_api_document/blob/doc/discourse.yml

**Comment by mohsen1** [comment]
Can't you just use two API key securities for this?

**Comment by webron** [comment]
@fantasticfears - really not sure what you're looking for here. As @mohsen1 mentioned, you can just declare two key security and say they are both required.

**Comment by fantasticfears** [comment]
Yes, I just missed that. :+1: Thanks for your help.
