### ISSUE TITLE
Feature Request: Support for general model documentation.

### ISSUE THREAD

**Issue by csmccoy** [swagger-api/swagger-spec#382]
Would it be possible to include the ability to document the model's so that they show somewhere, at the bottom for instance, of the page for reference purposes?  Use case would be an API has complex models implemented that would warrant additional documentation for a user beyond what is defined in the routes.  This would serve that purpose.

**Comment by webron** [comment]
@csmccoy - thanks for the issue, but can you open that on [swagger-ui](https://github.com/swagger-api/swagger-ui)? That's a specific issue for the UI and not general for the spec.

**Comment by csmccoy** [comment]
Done.
