### ISSUE TITLE
`schemes` description is unclear about default value

### ISSUE THREAD

**Issue by broofa** [swagger-api/swagger-spec#386]
Regarding the `schemes` property, from the spec:

> the default scheme to be used is the one used to access the specification

This is unclear.  How does one "access" the specification? (e.g. I'm currently reading the specification at `https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md` at the moment... so is the default scheme `https`?)

The specification should be explicit about the default scheme.  E.g. "If unspecified, the default value is `['http']`.

**Comment by webron** [comment]
Updated the wording, please let me know if's clearer now.

**Comment by broofa** [comment]
Got it, thanks!
