### ISSUE TITLE
Support multiple values for same querystring or form field key

### ISSUE THREAD

**Issue by stantonk** [swagger-api/swagger-spec#395]
It is relatively common for an endpoint to support the specification of a multiple values for the same querystring argument to imply an array of the same object type, e.g.:

`/api/report/?exclude_department=17&exclude_department=42`

This would produce a list of `exclude_department = [17, 42]` in the request handling code.

For instance, in Django, the `request.GET` and `request.POST` objects both support this:

```python
>>> QueryDict('a=1&a=2&c=3')
<QueryDict: {'a': ['1', '2'], 'c': ['3']}>
```
ref: https://docs.djangoproject.com/en/1.8/ref/request-response/#django.http.QueryDict

I may be mistaken, but as far as I can tell, this is not possible with swagger-spec at present, nor in swagger-ui.

**Comment by casualjim** [comment]
If you're on swagger 2.0 then you can use collectionFormat: multi on a parameter

https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#parameterObject

**Comment by webron** [comment]
@stantonk - as @casualjim kindly pointed out, this is already supported by the spec.
