### ISSUE TITLE
Extending one Definition to have definitions of different sizes

### ISSUE THREAD

**Issue by netei** [swagger-api/swagger-spec#402]
In the API I'm describing, I have some pretty deeply nested objects, where I have to write some huge definitions.

That is why our API also sometimes just returns only some properties of those full objects. 

Is they a way to specify that one Object definition extends one other (or is a projection, where we only keep some specified fields) ?

I have tried to write:

```yaml
UserMinimal:
  description: ...
  properties: 
    a:fjfjfj
    b:jfjfjf
User:
  $ref: '#/definitions/UserMinimal'
  description: ...
  properties: 
    c:fjfjfj
    d:jfjfjf
```

but in that case, User has only the properties of UserMinimal (eg `a` and `b`, not `c` and `d`, as I would expect)

**Comment by mohsen1** [comment]
In [Instagram API](https://github.com/swagger-api/swagger-editor/blob/master/app/spec-files/instagram.yaml) example I did something similar for User definition.

JSON Schema has `allOf` that can be used for extending one or more other schemas:

**Comment by webron** [comment]
As @mohsen1 explained (and his example shows it well), you can use [model composition](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#models-with-composition) for that. That's not hierarchical though, and if you're looking for that you're looking for inheritance.

In the future, please use the [google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket) for general support questions as that reaches a wider audience of people who can help.
