### ISSUE TITLE
swagger editor cannot be built behind a firewall

### ISSUE THREAD

**Issue by d-smith** [swagger-api/swagger-spec#415]
The swagger editor cannot be build on machines that have an HTTP proxy between them and the internet (commit b1b4582a3071f7dd3b2901dbee9beb01c69a23dc)

Before attempting to build swagger I had set http proxy environment variables (http_proxy, https_proxy, HTTP_PROXY, HTTPS_PROXY), set proxy settings via npm config proxy and https-proxy (and the registry too), plus modified .bowerrc to include proxy information.

Even with all the set, the build fails - see the [build output](https://gist.github.com/d-smith/15319900ccbd0fcbe40a)

According to some analysis by @jbarrus it appears to be related to [this issue](https://github.com/sindresorhus/got/issues/7)

To work around this (also as per @jbarrus), comment out line 13 in grunt/concurrent.js -- this will enable the build to complete successfully and the swagger editor to be served up.

<pre>
'use strict';

module.exports = {
  server: [
    'copy:styles'
  ],
  test: [
    'copy:styles',
  ],
  dist: [
    'copy:ace',
    'copy:styles',
//    'imagemin',
    'svgmin'
  ]
};
</pre>

**Comment by mohsen1** [comment]
You don't have to build it yourself. You can grab a built from [releases](https://github.com/swagger-api/swagger-editor/releases) download section

**Comment by webron** [comment]
@d-smith, if you still have problems, please open an issue directly on [swagger-editor](https://github.com/swagger-api/swagger-editor).
