### ISSUE TITLE
Conflicting AND / OR for security requirement object

### ISSUE THREAD

**Issue by chrisdudley** [swagger-api/swagger-spec#416]
In the list of child objects for the Swagger object (and Operation object) it says this for the security requirement object:

<pre>"there is a logical OR between the security requirements"</pre>

However in the detailed information about the Security Requirement object it says:

<pre>"that is, there is a logical AND between the schemes"</pre>

In practice it seems to be AND not OR. Can this be clarified please?

**Comment by webron** [comment]
The `security` field is an array of `Security Requirement` objects. There's a logical OR between the items in the `security` array and a logical AND between schemes described in a single `Security Requirement` object. In effect, this allows you to define compound security options by having several groups of security schemes (one or more scheme), allowing the user the option to pick between several schemes. There aren't many cases where this level of complexity is required, but it is available for those who need it.

Does that help?

**Comment by chrisdudley** [comment]
So this YAML:
<pre>security:
  - Client ID: []
  - Basic Authentication: []</pre>

Is that saying Client ID or basic auth?
How would I say both are needed?

**Comment by webron** [comment]
Like so:
```yaml
security:
  - Client ID: []
    Basic Authentication: []
```

**Comment by chrisdudley** [comment]
OK, thanks. I'd better go raise a defect on swagger editor for it not supporting that then ;-)
