### ISSUE TITLE
collectionFormat not allowed for array objects within a schema.

### ISSUE THREAD

**Issue by lostinthestory** [swagger-api/swagger-spec#419]
As defined in the spec, I can set `collectionFormat` if I create a parameter of type `array`.

    "parameters": [
          {
            "name": "test",
            "in": "header",
            "description": "testDesc",
            "required": true,
            "type": "array",
            "collectionFormat": "csv",
            "items": {
              "type": "number"
            }
          }
        ],

However, if I were to create a body parameter or something else that requires properties, I would expect the behavior to be the same.

However, if I define my schema as below, creating a property of type `array`, I receive an error from the validator, saying that I am not allowed to provide a `collectionFormat`

    "parameters": [
          {
            "name": "test",
            "in": "body",
            "description": "testDesc",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "testArray": {
                  "type": "array",
                  "collectionFormat": "csv",
                  "items": {
                    "type": "number"
                  },
                }
              }
            }
          }
        ],

If I remove the `collectionFormat` line from the code above, the validator accepts it.

**Comment by webron** [comment]
Actually, the spec doesn't allow for `collectionFormat` to be included in body parameters.

**Comment by lostinthestory** [comment]
Interesting, why would it be different between the two, with both being arrays?

**Comment by webron** [comment]
Body parameters are, in most cases, models which are normally described as JSON objects. JSON has its way of defining arrays (as does XML). The reason `collectionFormat` was added was to allow the flexibility for the other parameter types where there's no standard whatsoever for specifying how multiple values are sent.

**Comment by lostinthestory** [comment]
Ah, that's good to know! Thanks!
