### ISSUE TITLE
Omit Response Message

### ISSUE THREAD

**Issue by atrioom** [swagger-api/swagger-spec#434]
I searched quite a while how to silence error messages, I couldn't find it. Is it possible to omit the error message on, say, an InputError (eg. wrong content type)?
I want the API to silently deliver http status codes, but no in depth information what lies beneath. Ofc, in the server log there should be tons of information. What am I doing wrong?
Thank you and appologies if I seem to have misunderstood something.

**Comment by webron** [comment]
Are you referring to a specific tool? The Swagger specification is meant for documentation, so I don't follow how your question is relevant.

**Comment by atrioom** [comment]
I am using the swagger for nodejs package to build my project. The framework I use is express. I thought the 'issue' I am having is a purely swagger related one, but your question makes me quite unsure that is the case.

**Comment by webron** [comment]
Which specific tool do you use?

**Comment by atrioom** [comment]
Can you give me some more information about what kind of tool you mean? I'd say swagger-tools (or swagger-node).

**Comment by webron** [comment]
Right, that's exactly what I was referring to. Either swagger-tools or swagger-node. In that case, if there's a strong binding between the Swagger definition and the code and you want to overcome it, you need to open the issue on the relevant project. It has nothing to do with the spec itself.

**Comment by atrioom** [comment]
Alright, will do. Sorry for the misunderstanding and thank you!
