### ISSUE TITLE
response model as array of type - spec 1.2

### ISSUE THREAD

**Issue by GiladShoham** [swagger-api/swagger-spec#449]
Hi, 
I used to work with spec 1.1 and now i'm moving to spec 1.2.
i have an API which return an array of users.
in the old spec i defined it with 
```
"responseClass" : "List[user]"
```
but in the new spec the response class is not exist any more.
so i have tried some ways like:
```
"type" : "List[user]"
```
```
"type" : "array[user]"
```
```
"responseMessages" : [
                {"code" : 200, "message" : "ok", "responseModel": {"type" : "array", "items" : {"type" : "user"} } }
            ]
```

and a lot more.
i couldn't make it to shown as [{userName : string}] in swagger ui.
no matter what i did.

p.s - i succeeded to do it with spec 2.0 like this.
but i need it to work with spec 1.2.

```yaml
responses:
      '200':
        description: An array of users
        schema:
          type: array
          items:
            $ref: '#/definitions/user'
```
any help will be welcome.
Thx.

**Comment by webron** [comment]
In 1.2, the successful response is described in the operation itself and not the `responseMessages`.

For example:
```json
{
  "method": "GET",
  "summary": "Finds Pets by status",
  "notes": "Multiple status values can be provided with comma seperated strings",
  "type": "array",
  "items": {
    "$ref": "Pet"
  },
  "nickname": "findPetsByStatus",
  "parameters": [
    {
      "name": "status",
      "description": "Status values that need to be considered for filter",
      "defaultValue": "available",
      "required": true,
      "type": "string",
      "paramType": "query",
      "allowMultiple": true,
      "enum": [
        "available",
        "pending",
        "sold"
      ]
    }
  ],
  "responseMessages": [
    {
      "code": 400,
      "message": "Invalid status value"
    }
  ]
}
```

**Comment by GiladShoham** [comment]
Thanks you!!!
it worked.
i spent 2.5 days to make this work, and you give me the answer in a minute.
You are the man!

actually i already tried something like this, but because i have also define the successful in the responseMessages it override my operation's definition.

I have some more question, but the are not related to this, so if i will need some help, i will post it separately.

Big thanks to you!

**Comment by webron** [comment]
Thanks for the update. Keep in mind that for general support questions, the [google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket) may be a better place.

**Comment by carlin-q-scott** [comment]
@webron The [v1.2 API Spec](https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/schemas/v1.2/operationObject.json) doesn't have a type or items field for operations so where'd you get those from?
