### ISSUE TITLE
Using empty schema object does not work anymore

### ISSUE THREAD

**Issue by micovery** [swagger-api/swagger-spec#452]
Since this change,

https://github.com/swagger-api/swagger-spec/commit/9db746f2aab8b8b29c1765e61dc57ee4dd8c2a05

It's not possible anymore to specify an empty schema object in a response.

```json
{ }
```

I believe this is because of the "oneOf" operator:

```json
"oneOf": [
            {
              "$ref": "#/definitions/schema"
            },
            {
              "$ref": "#/definitions/fileSchema"
            }
          ]
```

since { } matches both schemas ... it fails validation.

A simple fix for this I think is to make the "type" field required for  "#/definitions/fileSchema"

**Comment by webron** [comment]
Thanks for reporting, I'll get it fixed. Do you experience the problem with any specific tool?

**Comment by micovery** [comment]
I see it as a validation error when using editor.swagger.io.

![image](https://cloud.githubusercontent.com/assets/1885394/9562693/63d10b12-4e28-11e5-95ac-8b423f0a325b.png)

```yaml
---
swagger: "2.0"
info:
  title: "Sample"
  version: "1.0.0"
basePath: "/sample"
paths:
  /test:
    get:
      summary: "Test API"
      description: Test API"
      responses:
        200:
          schema: {"type": "object" }
          description: "Operation Successful"
```

**Comment by webron** [comment]
Okay thanks. Keep in mind it'll take a bit for the fix to be included in the editor.

In general, we don't recommend using an empty schema, however it is valid.

**Comment by achew22** [comment]
This doesn't seem to be fixed on http://editor.swagger.io on Sunday December 27th 2015. Is that working as intended? Using the same code sample referenced above.
