### ISSUE TITLE
Swagger Editor shows error when re-using operation

### ISSUE THREAD

**Issue by yomexzo** [swagger-api/swagger-spec#453]
It appears the `$ref` key is not well supported with operations in the swagger editor. The editor shows the error below for the snippet following below

    ✖ Swagger Error
    Additional properties not allowed: definitions,responses,paths,security,tags,securityDefinitions,schemes,consumes,produces,basePath,host,info,swagger
    Jump to line 39
    Details
     Object
      code:  "OBJECT_ADDITIONAL_PROPERTIES"
      message:  "Additional properties not allowed: definitions,responses,paths,security,tags,securityDefinitions,schemes,consumes,produces,basePath,host,info,swagger"
       path: Array [2]
      0:  "paths"
      1:  "/users/goauth-url"
      level: 900

Snippet

    swagger: "2.0"
    info:
      version: 1.2.0
      title: THE API
      description: "The documentation"
      contact:
        email: "*******"
      version: v3
    host: *******
    basePath: /v3
    produces:
      - application/json
      # - application/xml
    consumes:
      - application/json
    schemes:
      - http
      - https
    securityDefinitions:
      query_param:
        name: access_token
        type: apiKey
        description: "`access_token` is the token provided by the login endpoint on successful login."
        in: query
      # bearer_token:
        # type: basic
        # description: "`Authorization: Bearer access_token_value`. You see 'Basic Authentication' because swagger does not have the 'bearer' option. The prefix has to be`Bearer`"
    tags:
      - name: Users
    security:
      - query_param: []
    paths:
      /users/basic-login:
        $ref: '{base_url}/operations/users#basic-login'

**Comment by webron** [comment]
This issue was moved to swagger-api/swagger-editor#611
