### ISSUE TITLE
swagger ui stuck at "fetching resource list:" (Uncaught TypeError: Cannot read property 'length' of null)

### ISSUE THREAD

**Issue by saurabhsyzhi** [swagger-api/swagger-spec#455]
I am trying to integrate swagger in the application and swagger ui is stuck at "fetching resource list: /api/swagger.json"

F12 on the browser indicates the below issue @ swagger-client.js line no. 626

Uncaught TypeError: Cannot read property 'length' of null

swagger-client.js: line no. 626
if(typeof param['enum'] !== 'undefined') {

I am using dropwizard-swagger 0.7 version with swagger-core / swagger-annotation / swagger-jaxrs / swagger-jersey2-jaxrs version of 1.5.1-M2.

I have tried to direct access the /api/swagger.json and I think the problem seems to be below "null" parameters returned in the json.

Any thoughts on the issue.

parameters: [
{
name: "type",
in: "query",
description: null,
required: false,
type: "string",
items: null,
collectionFormat: null,
default: null,
pattern: null,
format: null,
enum: null
}

**Comment by fehguy** [comment]
Hi, looks like you haven't included the `SwaggerSerializers` in your app.  The `null` fields will go away when you do.

**Comment by saurabhsyzhi** [comment]
My app has a dependency on the dropwizard-swaer 07.0 which included swagger-jersey2-jaxrs version of 1.5.1-M2 having SwaggerSerializers. Is there anything else I am missing?

When I run "api/swagger.yaml" it doesn't give me nulls fields but swagger.json do.

**Comment by dzhus** [comment]
Swagger-ui freezes with my spec at this message too. The console shows `Uncaught TypeError: Cannot read property '$ref' of null`

**Comment by webron** [comment]
Closing this issue as it's unrelated to swagger-spec. Please open the issue on the project causing the problem. @dzhus - in your case, it would be the library that generates that swagger.json as it is invalid (contains 'null' values).
