### ISSUE TITLE
using Dropwizard-Swagger , on swagger ui it's not displaying arrayList

### ISSUE THREAD

**Issue by nishubansal** [swagger-api/swagger-spec#463]
hi,

I am using dropwizard-swagger  0.7.0 bundle. I have a resource which takes list of some objects as request parameter .I have annotated my resource classes properly. But on Swagger-UI, model for Datatype - ArrayList<SourceRequest> is not displaying its showing something like-  Array[#/definitions/SourceRequest]

Please let me know how to fix this!!

**Comment by fehguy** [comment]
Hi, please open this in swagger-core.  This repo is just for spec issues.
