### ISSUE TITLE
Problem with `in: path` parameter definitions.

### ISSUE THREAD

**Issue by AmandaCameron** [swagger-api/swagger-spec#465]
It appears that either the spec site, or this schema is wrong.

The spec site says nothing of "required" being required under any circumstance, so I'm guessing that this was done in error?

https://github.com/swagger-api/swagger-spec/blob/master/schemas/v2.0/schema.json#L801

**Comment by fehguy** [comment]
It is true that path parameters are required.  The schema is enforcing that this is explicitly as you mentioned.

See here for the spec:

https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#fixed-fields-7

note:

```
If the parameter is in "path", this property is required and its value MUST be true.
```

**Comment by AmandaCameron** [comment]
Ah, I see. I'll fix my schema-generation then.
