### ISSUE TITLE
JSON-schema(-faker) support, mock data

### ISSUE THREAD

**Issue by ducin** [swagger-api/swagger-spec#472]
Hello Dear Swaggers!

Recently I came upon the [online swagger editor](http://editor.swagger.io/) and I can see that the example definition reminds me of JSON schema, e.g.
```
      responses:
        '200':
          description: An array of products
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
```
though it's in YAML instead of JSON.

My question is: have you been considering using [JSON-Schema-faker](https://github.com/json-schema-faker/json-schema-faker) to provide a way to define mock data for the API spec? JSON-Schema-faker is a superset of JSON Schema that *defines how to generate semantic mock data*. It's a specification + JS implementation. The benefit of combining those tools (swagger and json-schema-faker) together are:
* online auto-generated docs could also generate example data structures (real JSON content)
* standalone mock server for swagger data
and perhaps something more.

I can see that the [sway repository](https://www.npmjs.com/package/sway) by @whitlockjc is using json-schema-faker, but didn't manage to figure out what for yet.

I would appreciate any comments and ideas related to this topic.

**Comment by whitlockjc** [comment]
sway provides mocks already using json-schema-faker.

**Comment by ducin** [comment]
Hi @whitlockjc, can you provide me an example on how this works? An online example maybe?

If `json-schema-faker` is used by `sway`, does it mean, it's part of the swagger spec or not? Is `sway` an official extension? Is entire swagger tool stack compatible with `sway` so that swagger users can make use of `json-schema-faker`?

I'm pretty new to swagger tool stack, forgive me naive questions...

**Comment by webron** [comment]
json-schema-faker is just a data mocker... it's not a spec and is unrelated to Swagger directly. Supporting Swagger tools can use it, but that's pretty much as far as it goes.

**Comment by whitlockjc** [comment]
Agreed.  Let's take this offline @ducin in the sway project.  Open an issue for an example but know there are tests that use it and there is API documentation.

**Comment by webron** [comment]
Thanks @whitlockjc!
