### ISSUE TITLE
Polymorphism examples are incorrect in 2.0 spec

### ISSUE THREAD

**Issue by bkonetzny** [swagger-api/swagger-spec#490]
According to the indentation (YAML) and braces (JSON), the `Cat` and `Dog` of the [Models with Polymorphism Support](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#models-with-polymorphism-support) are not sub-properties of `definitions` but in the root of the swagger spec. I think correct defintion of `Cat` and `Dog` would be as part of the `definitions` property.

**Comment by webron** [comment]
Whoops, nice catch! Thanks a lot for the fix!
