### ISSUE TITLE
How to handle situation in which same request path but different parameters?

### ISSUE THREAD

**Issue by kenmick** [swagger-api/swagger-spec#494]
For example, for a request like this: `GET /example.com/api/user`.
I have two paramters `name` and `id` which are sent in `query`. If I separate them to two requests, the latter will override the former. I believe it is because these two requests share the same path and method.

But how to handle this kind of situation?

Thanks in advance.

**Comment by webron** [comment]
The current version of Swagger doesn't support that. You can define both query parameters under a single operation but can't say the parameters are mutually exclusive. A unique operation in Swagger is currently considered a combination of the HTTP verb and the path. Other parameter types play no role in the uniqueness of an API and as such operation definitions would clobber each other.

There have been requests (here) to change that in the future so feel free to browser around the open issues and voice your opinion.

**Comment by kenmick** [comment]
Got it.
Thank you for your reply :)
