### ISSUE TITLE
'flow' vs 'grant' 

### ISSUE THREAD

**Issue by shtrived** [swagger-api/swagger-spec#497]
Just out of curiosity. Within security definitions, for schemes of "oauth2" type ... why the spec uses the term "flow" (as opposed to "grant")?

```json
"petstore_auth": {
    "type": "oauth2",
    "authorizationUrl": "http://swagger.io/api/oauth/dialog",
    "flow": "implicit",
    "scopes": {
      "write:pets": "modify pets in your account",
      "read:pets": "read your pets"
    }
  }
```

**Comment by webron** [comment]
Just a different term for the same thing. From http://oauth.net/2 (highlighting not in origin):

>  OAuth 2.0 focuses on client developer simplicity while providing specific authorization **flows** for web applications, desktop applications, mobile phones, and living room devices.

**Comment by shtrived** [comment]
Thanks Ron.

**Comment by webron** [comment]
Are we good to close this or do you have followup questions?

**Comment by shtrived** [comment]
We are good thanks.
