### ISSUE TITLE
Is there a way to restrict one parameter by using another one?

### ISSUE THREAD

**Issue by kenmick** [swagger-api/swagger-spec#499]
In this case,  `GET http://api.example.com/message/search` has two parameters in `query`, one is `begin`(long), another one is `end`(long). Obviously `begin` should less than `end`. Is the a way to add restriction in Swagger definition to make sure `begin` is less than `end`? something like `required: true`?

Thanks in advance.

**Comment by wing328** [comment]
Not that I'm aware of. You can get the official answer from https://github.com/swagger-api/swagger-parser.

**Comment by wing328** [comment]
Based on my understanding, it's not possible at the moment.

**Comment by webron** [comment]
It's not possible. Please follow #256.
