### ISSUE TITLE
How to describe a "hash" in a get request

### ISSUE THREAD

**Issue by ceritium** [swagger-api/swagger-spec#506]
Hello, I have to describe in swagger an API that send a hash of params with a get.

The documented request is like:

`curl -v  -X GET "https://example.com/usage.xml?api_key=1234&usage[hits]=1&usage[megas]=122"`

In the server they get something like:

```
usage: {
  hits: 1,
  megas: 122
}
```
You can send as many attributes as  you want.

How I can describe this kind of request with swagger 2.0?

Thanks!

**Comment by andrewdavidmackenzie** [comment]
Anyone got any ideas to help describe this issue?

**Comment by fehguy** [comment]
That's a non-standard query syntax and it's currently not supported in the spec.  I believe there's an open issue for this.

**Comment by webron** [comment]
As @fehguy mentioned, this is currently not supported in the spec. Please follow #380 and #367.

**Comment by ceritium** [comment]
Thanks!
