### ISSUE TITLE
Parameter file type consumes, confusing language

### ISSUE THREAD

**Issue by vanderlee** [swagger-api/swagger-spec#512]
In the Parameter Object definition of the type property, the following is stated:

> If type is "file", the consumes MUST be either "multipart/form-data" or "application/x-www-form-urlencoded"

Interpreting this strictly would mean that `consumes` MAY NOT contain both "multipart/form-data" and "application/x-www-form-urlencoded" but MUST contain no more or less than one of those two choices. This restriction seems odd to me.
Could anybody please clarify if the above interpretation is correct.

**Comment by webron** [comment]
It can be either one or both.

**Comment by vanderlee** [comment]
So basically "A and/or B" rather than "either A or B" (http://dictionary.cambridge.org/dictionary/english/either-or)

This language construct appears to be used in a few other places in the documentation as well, I believe some of those may similarly be incorrect.

**Comment by webron** [comment]
Please do. I'll review the changes and add comments if needed.

**Comment by vanderlee** [comment]
Just added a pull request #514. Only two found. Other uses of "either/or" seem appropriate as is.

**Comment by webron** [comment]
Thanks for that.
