### ISSUE TITLE
API version format is too strict

### ISSUE THREAD

**Issue by 0x62ash** [swagger-api/swagger-spec#517]
I don't see any limitation for version from spec:

> `version`	`string`	**Required** Provides the version of the application API (not to be confused with the specification version).

But I get error for `version: 0.1` :

>  Swagger Error
> A semantic version number of the API.
> Jump to line 10

**Comment by webron** [comment]
You're getting that error *where*?

**Comment by 0x62ash** [comment]
Here - http://editor.swagger.io/#/

**Comment by webron** [comment]
In that case...

**Comment by webron** [comment]
This issue was moved to swagger-api/swagger-editor#733
