### ISSUE TITLE
Byte/password type format missing in Swagger's JSON schema and swagger-core

### ISSUE THREAD

**Issue by quilicicf** [swagger-api/swagger-spec#518]
### Issue

The [spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#data-types) defines the data types _byte & password_. These types are neither in the [JSON schema](https://github.com/swagger-api/swagger-spec/blob/master/schemas/v2.0/schema.json) nor in the [parser](https://github.com/swagger-api/swagger-core/tree/master/modules/swagger-models/src/main/java/io/swagger/models/properties).

Should it be removed from the HTML doc or added in the JSON schema/parser ?

**Comment by webron** [comment]
The spec defines data *formats* not data *types*. The JSON Schema doesn't get into the formats, the parser could (and in that case, the issue should be opened on swagger-core).

**Comment by quilicicf** [comment]
Thanks @webron. I opened a PR on swagger-core.
