### ISSUE TITLE
Any plans for supporting multipart/related?

### ISSUE THREAD

**Issue by tleyden** [swagger-api/swagger-spec#520]
For [openocr](http://docs.openocr.apiary.io/#reference/openocr/ocr-decode-via-file-upload/ocr-decode) I used `multipart/related` ([rfc2112](https://tools.ietf.org/html/rfc2112)) for uploading image data via a REST API, and was wondering if Swagger is currently able to support this and/or planning to support this?

Is there a more common way of uploading multiple binary raw data chunks via a REST API than `multipart/related`?

**Comment by webron** [comment]
Seems like we need to expand support to multipart in general. Perhaps it'd be better to keep all suggestions under #303.
